import { heroui } from "@heroui/react";

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/presentation/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
      },
      fontSize: {
        "display-large": ["57px", { lineHeight: "64px", fontWeight: "400" }],
        "display-medium": ["45px", { lineHeight: "52px", fontWeight: "400" }],
        "display-small": ["36px", { lineHeight: "44px", fontWeight: "400" }],
        "headline-large": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-medium": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-small": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "title-large": ["22px", { lineHeight: "28px", fontWeight: "400" }],
        "title-medium": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "title-small": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-large": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-small": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-large": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-small": ["11px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "28px",
        full: "9999px",
      },
      colors: {
        primary: "#00897B",
        "on-primary": "#FFFFFF",
        "primary-container": "#B2DFDB",
        "on-primary-container": "#004D40",

        surface: "#FAFAFA",
        "on-surface": "#1C1B1F",
        "on-surface-variant": "#757575",
        "surface-container-low": "#F5F5F5",
        "surface-container": "#EEEEEE",
        "surface-container-high": "#FFFFFF",
        "surface-container-highest": "#E0E0E0",

        success: "#4CAF50",
        "success-container": "#C8E6C9",
        "on-success-container": "#1B5E20",

        error: "#F44336",
        "error-container": "#FFCDD2",
        "on-error-container": "#B71C1C",

        outline: "#E0E0E0",
        "outline-variant": "#BDBDBD",

        secondary: "#625B71",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E8DEF8",
        "on-secondary-container": "#1D192B",

        tertiary: "#7D5260",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#FFD8E4",
        "on-tertiary-container": "#31111D",

        dark: {
          surface: "#1C1B1F",
          "surface-dim": "#141316",
          "surface-bright": "#3B383E",
          "surface-container-lowest": "#0F0E11",
          "surface-container-low": "#1D1B1E",
          "surface-container": "#211F26",
          "surface-container-high": "#2B2930",
          "surface-container-highest": "#36343B",

          "on-surface": "#E6E1E5",
          "on-surface-variant": "#C7C6D0",
          "on-surface-dim": "#938F99",

          outline: "#8E9099",
          "outline-variant": "#44474E",

          primary: "#4FD8D8",
          "on-primary": "#003738",
          "primary-container": "#004F50",
          "on-primary-container": "#6FF7F7",
          "primary-border": "#00A6A6",

          success: "#6FDD8B",
          "on-success": "#00390F",
          "success-container": "#005319",
          "on-success-container": "#B7F3C6",
          "success-border": "#4CAF50",

          error: "#FFB4AB",
          "on-error": "#690005",
          "error-container": "#93000A",
          "on-error-container": "#FFDAD6",
          "error-border": "#EF5350",

          warning: "#FFB951",
          "on-warning": "#492900",
          "warning-container": "#6A4000",
          "on-warning-container": "#FFDDB5",
        },
      },
    },
  },
  darkMode: "class",
  plugins: [
    heroui({
      themes: {
        light: {
          colors: {
            background: "#FFFBFE",
            foreground: "#1C1B1F",
            primary: {
              50: "#F2E7FE",
              100: "#D9C2FD",
              200: "#BF9EFC",
              300: "#A579FB",
              400: "#8B55FA",
              500: "#6750A4",
              600: "#5F4698",
              700: "#563C8C",
              800: "#4E3280",
              900: "#452874",
              DEFAULT: "#6750A4",
              foreground: "#FFFFFF",
            },
            secondary: {
              DEFAULT: "#625B71",
              foreground: "#FFFFFF",
            },
            success: {
              DEFAULT: "#2E7D32",
              foreground: "#FFFFFF",
            },
            warning: {
              DEFAULT: "#EF6C00",
              foreground: "#FFFFFF",
            },
            danger: {
              DEFAULT: "#B3261E",
              foreground: "#FFFFFF",
            },
            default: {
              50: "#FDFBFF",
              100: "#F8F5FA",
              200: "#F2EFF4",
              300: "#ECE9EE",
              400: "#E6E3E8",
              500: "#E0DDE2",
              600: "#DAD7DC",
              700: "#D4D1D6",
              800: "#CECBD0",
              900: "#C8C5CA",
              DEFAULT: "#FFFBFE",
              foreground: "#1C1B1F",
            },
            "primary-container": "#EADDFF",
            "on-primary-container": "#21005D",
            "secondary-container": "#E8DEF8",
            "on-secondary-container": "#1D192B",
            tertiary: "#7D5260",
            "on-tertiary": "#FFFFFF",
            "tertiary-container": "#FFD8E4",
            "on-tertiary-container": "#31111D",
            "surface-variant": "#E7E0EC",
            "on-surface-variant": "#49454F",
            outline: "#79747E",
          },
          layout: {
            disabledOpacity: "0.38",
            radius: {
              small: "8px",
              medium: "12px",
              large: "16px",
              xl: "28px",
            },
            borderWidth: {
              small: "1px",
              medium: "2px",
              large: "3px",
            },
          },
        },
        dark: {
          colors: {
            background: "#1C1B1F",
            foreground: "#E6E1E5",
            primary: {
              50: "#21005D",
              100: "#381E72",
              200: "#4F378B",
              300: "#6750A4",
              400: "#7F67BE",
              500: "#9A82DB",
              600: "#B69DF8",
              700: "#D0BCFF",
              800: "#EADDFF",
              900: "#F6EDFF",
              DEFAULT: "#D0BCFF",
              foreground: "#381E72",
            },
            secondary: {
              DEFAULT: "#CCC2DC",
              foreground: "#332D41",
            },
            success: {
              DEFAULT: "#B7F397",
              foreground: "#003909",
            },
            warning: {
              DEFAULT: "#FFB74D",
              foreground: "#4E2600",
            },
            danger: {
              DEFAULT: "#F2B8B5",
              foreground: "#601410",
            },
            default: {
              50: "#1C1B1F",
              100: "#25232A",
              200: "#312E36",
              300: "#3C3941",
              400: "#48444D",
              500: "#544F59",
              600: "#605B65",
              700: "#6D6771",
              800: "#79737E",
              900: "#867F8A",
              DEFAULT: "#1C1B1F",
              foreground: "#E6E1E5",
            },
            "primary-container": "#4F378B",
            "on-primary-container": "#EADDFF",
            "secondary-container": "#4A4458",
            "on-secondary-container": "#E8DEF8",
            tertiary: "#EFB8C8",
            "on-tertiary": "#492532",
            "tertiary-container": "#633B48",
            "on-tertiary-container": "#FFD8E4",
            "surface-variant": "#49454F",
            "on-surface-variant": "#CAC4D0",
            outline: "#938F99",
          },
        },
      },
    }),
  ],
};
